version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    image: postgres_timescale_postgis
    ports:
      - 5432:5432
    env_file:
      .envs/.production/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
